import { chromium, request } from "playwright";

const FRONTEND_BASE_URL = process.env.E2E_BASE_URL || "http://127.0.0.1:9010";
const API_BASE_URL = process.env.E2E_API_BASE_URL || "http://127.0.0.1:8080";
const PASSWORD = process.env.E2E_TEST_PASSWORD || "AgroDzz123!";
const TEST_POLYGON = [
  { longitude: 37.6, latitude: 55.76 },
  { longitude: 37.62, latitude: 55.76 },
  { longitude: 37.622, latitude: 55.751 },
  { longitude: 37.602, latitude: 55.749 },
  { longitude: 37.6, latitude: 55.76 },
];

function appUrl(pathWithQuery) {
  return `${FRONTEND_BASE_URL}${pathWithQuery}`;
}

async function assertOk(response, label) {
  if (response.ok()) {
    return;
  }
  const body = await response.text();
  throw new Error(`${label} failed: ${response.status()} ${body}`);
}

async function createAndLoginUser(apiRequest, email) {
  const registerResponse = await apiRequest.post(`${API_BASE_URL}/api/auth/register`, {
    data: {
      email,
      text_password: PASSWORD,
      role: "organization",
    },
  });
  await assertOk(registerResponse, "User registration");

  const loginResponse = await apiRequest.post(`${API_BASE_URL}/api/auth/token`, {
    form: {
      username: email,
      password: PASSWORD,
    },
  });
  await assertOk(loginResponse, "User login");
  const tokenPayload = await loginResponse.json();
  return tokenPayload.access_token;
}

async function createDzzCandidate(apiRequest, token) {
  const headers = {
    Authorization: `Bearer ${token}`,
  };
  const now = new Date();
  const seasonStart = new Date(now);
  seasonStart.setMonth(now.getMonth() - 2);
  const seasonEnd = new Date(now);
  seasonEnd.setMonth(now.getMonth() + 4);

  const seasonName = `E2E season ${Date.now()}`;
  const seasonResponse = await apiRequest.post(`${API_BASE_URL}/api/fields-service/season`, {
    headers,
    data: {
      season: "SeasonBaseDTO",
      name: seasonName,
      startDate: seasonStart.toISOString().slice(0, 10),
      endDate: seasonEnd.toISOString().slice(0, 10),
    },
  });
  await assertOk(seasonResponse, "Create season");
  const seasonPayload = await seasonResponse.json();
  const seasonId = seasonPayload.id;

  const fieldName = `E2E field ${Date.now()}`;
  const fieldResponse = await apiRequest.post(
    `${API_BASE_URL}/api/fields-service/seasons/${seasonId}/field`,
    {
      headers,
      data: {
        field: "FieldDTO",
        name: fieldName,
        description: "Autogenerated DZZ e2e field",
        contours: [
          {
            contour: "ContourBaseDTO",
            name: "E2E contour",
            color: "2f6fdd",
            squareArea: "1000",
            coordinates: TEST_POLYGON,
          },
        ],
      },
    }
  );
  await assertOk(fieldResponse, "Create field");
  const fieldPayload = await fieldResponse.json();
  const fieldId = fieldPayload.id;

  const contoursResponse = await apiRequest.get(
    `${API_BASE_URL}/api/fields-service/fields/${fieldId}/contours`,
    { headers }
  );
  await assertOk(contoursResponse, "Get field contours");
  const contours = await contoursResponse.json();
  if (!Array.isArray(contours) || contours.length === 0) {
    throw new Error("Created field has no contours.");
  }

  const contour = contours[0];
  const cropRotationResponse = await apiRequest.post(
    `${API_BASE_URL}/api/fields-service/contours/${contour.id}/crop-rotation`,
    {
      headers,
      data: {
        culture: "Пшеница красная яровая",
        cultivar: "E2E cultivar",
        startDate: seasonStart.toISOString().slice(0, 10),
        endDate: seasonEnd.toISOString().slice(0, 10),
        description: "Autogenerated DZZ crop rotation",
      },
    }
  );
  await assertOk(cropRotationResponse, "Create crop rotation");

  const dzzResponse = await apiRequest.get(`${API_BASE_URL}/api/dzz/${fieldId}`, {
    headers,
    params: { seasonId },
  });
  await assertOk(dzzResponse, "Load DZZ dashboard");
  const dashboard = await dzzResponse.json();
  if (!Array.isArray(dashboard.catalog) || dashboard.catalog.length < 2) {
    throw new Error("DZZ dashboard has less than two scenes for the generated field.");
  }
  if (
    !dashboard.culture_context ||
    Number(dashboard.culture_context.contours_with_culture || 0) < 1
  ) {
    throw new Error("DZZ dashboard has no culture context for the generated field.");
  }

  return {
    season: { id: seasonId, name: seasonName },
    field: { id: fieldId, name: fieldName },
    dashboard,
  };
}

async function run() {
  const email = `dzz-e2e-${Date.now()}@example.com`;
  const apiRequest = await request.newContext({ timeout: 180000 });
  const token = await createAndLoginUser(apiRequest, email);
  const candidate = await createDzzCandidate(apiRequest, token);

    const browser = await chromium.launch({ headless: true, channel: "chrome" });
  const context = await browser.newContext();
  const page = await context.newPage();

  try {
    await page.goto(`${FRONTEND_BASE_URL}/login`, { waitUntil: "networkidle" });
    await page.locator('input[type="email"]').fill(email);
    await page.locator('input[type="password"]').fill(PASSWORD);
    await page.getByRole("button", { name: "Войти" }).click();
    await page.waitForURL(/\/map/, { timeout: 30000 });

    const targetUrl =
      `${appUrl("/field_dzz_info")}` +
      `?seasonId=${encodeURIComponent(candidate.season.id)}` +
      `&seasonName=${encodeURIComponent(candidate.season.name)}` +
      `&fieldId=${encodeURIComponent(candidate.field.id)}` +
      `&fieldName=${encodeURIComponent(candidate.field.name)}`;

    await page.goto(targetUrl, { waitUntil: "networkidle" });

    await page.getByText("Контекст по культуре", { exact: true }).waitFor({ timeout: 30000 });
    await page
      .getByText("Карта индекса внутри поля", { exact: true })
      .waitFor({ timeout: 30000 });
    await page
      .getByText("Временной ряд индексов", { exact: true })
      .waitFor({ timeout: 30000 });
    await page.getByText("Каталог сцен", { exact: true }).waitFor({ timeout: 30000 });
    await page.locator("#dzz-field-map").waitFor({ timeout: 30000 });
    await page.locator(".leaflet-image-layer").first().waitFor({ timeout: 30000 });

    const uniqueSceneDates = [...new Set(candidate.dashboard.catalog.map((scene) => scene.scene_date))].sort();
    const initialCatalogCount = await page.locator(".catalog-item").count();
    if (uniqueSceneDates.length >= 2) {
      await page.getByLabel("Дата начала").fill(uniqueSceneDates[uniqueSceneDates.length - 2]);
      await page.getByLabel("Дата окончания").fill(uniqueSceneDates[uniqueSceneDates.length - 1]);
      await page.waitForLoadState("networkidle");

      const filteredCatalogCount = await page.locator(".catalog-item").count();
      if (filteredCatalogCount > initialCatalogCount) {
        throw new Error("Date filter did not narrow the scene catalog.");
      }
    }

    await page.locator(".compare-toggle .q-toggle").click();
    await page.getByText("Сравнение двух дат", { exact: true }).waitFor({ timeout: 30000 });
    await page.getByText("Средняя дельта", { exact: true }).waitFor({ timeout: 30000 });

    await page.getByRole("button", { name: "Обновить данные" }).click();
    await page
      .getByText("Свежие ДЗЗ-данные загружены", { exact: true })
      .waitFor({ timeout: 30000 });

    console.log(
      JSON.stringify({
        status: "ok",
        fieldId: candidate.field.id,
        fieldName: candidate.field.name,
        seasonId: candidate.season.id,
        seasonName: candidate.season.name,
      })
    );
  } finally {
    await context.close();
    await browser.close();
    await apiRequest.dispose();
  }
}

run().catch((error) => {
  console.error(error);
  process.exit(1);
});
